const Products = [
  {
    id: 1,
    category: "grains-and-cereals",
    image: "/images/Maize.jpeg",
    alt: "maize image",
    name: "Maize",
    quantity: "30g",
    price: "GHS 40.00",
    location: "Kumasi",
  },
  {
    id: 2,
    category: "grains-and-cereals",
    image: "/images/Rice.jpeg",
    alt: "rice image",
    name: "Rice",
    quantity: "30g",
    price: "GHS 20.00",
    location: "Sunyani",
  },
  {
    id: 3,
    category: "grains-and-cereals",
    image: "/images/Wheat.jpeg",
    alt: "wheat image",
    name: "Wheat",
    quantity: "50g",
    price: "GHS 20.00",
    location: "Accra",
  },
  {
    id: 4,
    category: "grains-and-cereals",
    image: "/images/Millet.jpeg",
    alt: "millet image",
    name: "Millet",
    quantity: "5g",
    price: "GHS 5.00",
    location: "Cape Coast",
  },
  {
    id: 5,
    category: "fruits",
    image: "/images/Coconuts.jpeg",
    alt: "coconut image",
    name: "Coconuts",
    quantity: "30g",
    price: "GHS 35.00",
    location: "Takoradi",
  },
  {
    id: 6,
    category: "roots-and-tubers",
    image: "/images/Yams.jpeg",
    alt: "yams image",
    name: "Yams",
    quantity: "30g",
    price: "GHS 35.00",
    location: "Kumasi",
  },
  {
    id: 7,
    category: "fruits",
    image: "/images/Banana.jpeg",
    alt: "banana image",
    name: "Banana",
    quantity: "30g",
    price: "GHS 35.00",
    location: "Accra",
  },
  {
    id: 8,
    category: "roots-and-tubers",
    image: "/images/Potatoes.jpeg",
    alt: "potatoes image",
    name: "Potatoes",
    quantity: "30g",
    price: "GHS 35.00",
    location: "Sunyani",
  },
  {
    id: 9,
    category: "vegetables",
    image: "/images/Tomatoes.jpeg",
    alt: "tomatoes image",
    name: "Tomatoes",
    quantity: "30g",
    price: "GHS 35.00",
    location: "Takoradi",
  },
  {
    id: 10,
    category: "vegetables",
    image: "/images/Onions.jpeg",
    alt: "onions image",
    name: "Onions",
    quantity: "30g",
    price: "GHS 35.00",
    location: "Cape Coast",
  },
  {
    id: 11,
    category: "vegetables",
    image: "/images/Garlic.jpeg",
    alt: "garlic image",
    name: "Garlic",
    quantity: "30g",
    price: "GHS 35.00",
    location: "Koforidua",
  },
  {
    id: 12,
    category: "vegetables",
    image: "/images/Carrots.jpeg",
    alt: "carrots image",
    name: "Carrots",
    quantity: "30g",
    price: "GHS 35.00",
    location: "Accra",
  },
  {
    id: 13,
    category: "legumes-and-pulses",
    image: '/images/Peanuts.jpeg',
    alt: 'peanuts image',
    name: "Peanuts",
    quantity: '50g',
    price: 'GHS 20.00',
    location: "Kumasi"
  },
  {
    id: 14,
    category: "vegetables",
    image: "/images/Cabbage.jpeg",
    alt: "cabbage image",
    name: "Cabbage",
    quantity: "30g",
    price: "GHS 35.00",
    location: "Takoradi",
  },
  {
    id: 15,
    category: "vegetables",
    image: "/images/Lettuce.jpeg",
    alt: "lettuce image",
    name: "Lettuce",
    quantity: "30g",
    price: "GHS 35.00",
    location: "Tamale",
  },
  {
    id: 16,
    category: "roots-and-tubers",
    image: "/images/Cocoyam.jpeg",
    alt: "cocoyam image",
    name: "Cocoyams",
    quantity: "30g",
    price: "GHS 35.00",
    location: "Sefwi",
  },
  {
    id: 17,
    category: "vegetables",
    image: "/images/Green-Beans.jpeg",
    alt: "green beans image",
    name: "Green Beans",
    quantity: "30g",
    price: "GHS 35.00",
    location: "Kumasi",
  },
  {
    id: 18,
    category: "legumes-and-pulses",
    image: '/images/Soybeans.jpeg',
    alt: 'soybeans image',
    name: "Soybeans",
    quantity: '30g',
    price: 'GHS 30.00',
    location: "Accra"
  },
  {
    id: 19,
    category: "vegetables",
    image: "/images/Peppers.jpeg",
    alt: "peppers image",
    name: "Peppers",
    quantity: "30g",
    price: "GHS 35.00",
    location: "Accra",
  },
  {
    id: 20,
    category: "vegetables",
    image: "/images/cucumber.webp",
    alt: "cucumber image",
    name: "Cucumbers",
    quantity: "30g",
    price: "GHS 35.00",
    location: "Tamale",
  },
  {
    id: 21,
    category: "vegetables",
    image: "/images/Okra.jpeg",
    alt: "okra image",
    name: "Okra",
    quantity: "30g",
    price: "GHS 35.00",
    location: "Koforidua",
  },
  {
    id: 22,
    category: "vegetables",
    image: "/images/Eggplant.jpeg",
    alt: "eggplant image",
    name: "Eggplant",
    quantity: "30g",
    price: "GHS 35.00",
    location: "Sefwi",
  },
  {
    id: 23,
    category: "fruits",
    image: "/images/Plantain.jpeg",
    alt: "plantain image",
    name: "Plantains",
    quantity: "30g",
    price: "GHS 35.00",
    location: "Sunyani",
  },
  {
    id: 24,
    category: "fruits",
    image: "/images/Pineapple.jpeg",
    alt: "pineapple image",
    name: "Pineapples",
    quantity: "30g",
    price: "GHS 35.00",
    location: "Takoradi",
  },
  {
    id: 25,
    category: "legumes-and-pulses",
    image: '/images/Chickpeas.jpeg',
    alt: 'chickpeas image',
    name: "Chickpeas",
    quantity: '30g',
    price: 'GHS 25.00',
    location: "Tamale"
  },
  {
    id: 26,
    category: "fruits",
    image: "/images/Mangoes.jpeg",
    alt: "mangoes image",
    name: "Mangoes",
    quantity: "30g",
    price: "GHS 35.00",
    location: "Tamale",
  },
  {
    id: 27,
    category: "legumes-and-pulses",
    image: '/images/KidneyBeans.jpeg',
    alt: 'kidney beans image',
    name: "Kidney Beans",
    quantity: '30g',
    price: 'GHS 15.00',
    location: "Sunyani"
  },
  {
    id: 28,
    category: "fruits",
    image: "/images/Oranges.jpeg",
    alt: "oranges image",
    name: "Oranges",
    quantity: "30g",
    price: "GHS 35.00",
    location: "Accra",
  },
  {
    id: 29,
    category: "fruits",
    image: "/images/Lemon.jpeg",
    alt: "lemon image",
    name: "Lemons",
    quantity: "30g",
    price: "GHS 35.00",
    location: "Kumasi",
  },
  {
    id: 30,
    category: "fruits",
    image: "/images/Avocado.jpeg",
    alt: "avocado image",
    name: "Avocados",
    quantity: "30g",
    price: "GHS 35.00",
    location: "Tamale",
  },
  {
    id: 31,
    category: "fruits",
    image: "/images/Apple.jpeg",
    alt: "apple image",
    name: "Apple",
    quantity: "30g",
    price: "GHS 35.00",
    location: "Cape Coast",
  },
  {
    id: 32,
    category: "nuts-and-seeds",
    image: "/images/Cashew.jpeg",
    alt: "cashew image",
    name: "Cashew",
    quantity: "30g",
    price: "GHS 35.00",
    location: "Sunyani",
  },
  {
    id: 33,
    category: "nuts-and-seeds",
    image: "/images/Groundnut.jpeg",
    alt: "groundnut image",
    name: "Groundnuts",
    quantity: "30g",
    price: "GHS 9.00",
    location: "Takoradi",
  },
  {
    id: 34,
    category: "fruits",
    image: "/images/Grapes.jpeg",
    alt: "grapes image",
    name: "Grapes",
    quantity: "300g",
    price: "GHS 25.00",
    location: "Sefwi",
  },
  {
    id: 35,
    category: "herbs-and-spices",
    image: "/images/Ginger.jpeg",
    alt: "ginger image",
    name: "Ginger",
    quantity: "30g",
    price: "GHS 10.00",
    location: "Tamale",
  },
  {
    id: 36,
    category: "fruits",
    image: "/images/Watermelon.jpeg",
    alt: "watermelon image",
    name: "Watermelon",
    quantity: "300g",
    price: "GHS 5.00",
    location: "Sunyani",
  },
];

export default Products;